# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djsgerp', '0002_auto_20161119_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantrypriceelement',
            name='daytype',
            field=models.CharField(default='Weekdays', max_length=20, verbose_name='Day Type'),
        ),
        migrations.AlterField(
            model_name='gantrypriceelement',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djsgerp.VehicleType', verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='gantrypriceelement',
            name='zone_id',
            field=models.CharField(max_length=10, verbose_name='Zone ID'),
        ),
    ]
