# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsgerp', '0004_gantrypriceelement_charge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantryposition',
            name='external_id',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='gantryposition',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Gantry position name'),
        ),
    ]
